In [1]:
import numpy as np

## DataTypes & Attributes
Numpy's main datatype is ndarray

In [4]:
# n-dimensional array
a1 = np.array([1, 2, 3])
a1

array([1, 2, 3])

In [5]:
type(a1)

numpy.ndarray

In [6]:
a2 = np.array([
    [1,2],
    [3.4, 4.2]
])

a3 = np.array([[[1,2],[3,4]],[[5,6],[7,8]],[[9,10],[11,12]]])

In [10]:
a2, a2.ndim

(array([[1. , 2. ],
        [3.4, 4.2]]),
 2)

In [11]:
a3, a3.ndim

(array([[[ 1,  2],
         [ 3,  4]],
 
        [[ 5,  6],
         [ 7,  8]],
 
        [[ 9, 10],
         [11, 12]]]),
 3)

## NumPy Attributes

`.shape` returns the shape of each elements in the array  
`.ndim` returns the dimensions of the array  
`.dtype` returns the data types of the elements in the array  
`.size` returns the number of elements in the array, total (deep)  


## Creating a DataFrame from a NumPy Array

In [15]:
import pandas as pd
df = pd.DataFrame(a2)
df

0    1
0  1.0  2.0
1  3.4  4.2

## 2. Creating NumPy Arrays

In [17]:
sample_array = np.array([1,2,3])
sample_array

array([1, 2, 3])

`np.ones(shape, dtype=None, order='C')`  
Returns a new array of given shape and type
returns an array filled with `1.0` that matches the shape.  
`np.zeroes(shape, dtype=None, order='C')`  
Returns a new array of given shape and type
returns an array filled with `0.0` that matches the shape.

In [18]:
ones = np.ones((2,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [19]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [22]:
random_array = np.random.randint(0,10, size=(3,5))
random_array

array([[2, 3, 8, 8, 2],
       [9, 6, 4, 9, 9],
       [4, 7, 0, 6, 5]])

In [26]:
### Pseudo-random numbers
np.random.seed(0)
random_array_2 = np.random.randint(10, size=(5,3))
random_array_2

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

## 3. Viewing Arrays and Manipulating Arrays

In [28]:
a2[:2]
#  It's just like slicing an array.

array([[1. , 2. ],
       [3.4, 4.2]])

In [32]:
a3[:1,:1,:1]
# When dealing with multiple dimensions, you just use comma to separate the slicing logic

array([[[1]]])

## 4. Manipulating & Comparing Arrays

### Arithmetic

In [36]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [37]:
ones + a1

array([[2., 3., 4.],
       [2., 3., 4.]])